model_name: Panoptic_PolarNet

TRAIN:
    learning_rate: 0.001
    weight_decay: 1e-4 
dataset:
    name: semantickitti
    path: ../semanticKITTI/dataset
    output_path: out/SemKITTI
    instance_pkl_path: ../semanticKITTI/panoptic_polarnet_preproc
    type: voxel # voxel or points
    rotate_aug: False
    flip_aug: False    
    inst_aug: False
    inst_aug_type:
        inst_os: False
        inst_loc_aug: False
        inst_global_aug: False
    gt_generator:
        sigma: 5
    grid_size: [256,256,32]

model:
    model_save_path: ./weights/Panoptic_SemKITTI.pt
    voxel_instance_model_save_path: ./weights/
    pretrained_model: /pretrained_weight/Panoptic_SemKITTI_PolarNet.pt
    bev_save_path: ./weights/BEV_SemKITTI.pt
    train_log: ./weights
    polar: False
    visibility: False
    
    train_batch_size: 16
    val_batch_size: 1
    test_batch_size: 1
    check_iter: 4000
    max_epoch: 100
    post_proc:
        threshold: 0.1
        nms_kernel: 5
        top_k: 100
    center_loss: MSE
    offset_loss: L1
    center_loss_weight: 100
    offset_loss_weight: 10
    enable_SAP: True
    SAP:
        start_epoch: 30
        rate: 0.01