DATALOADER:
  NUM_WORKERS: 4
DATASET:
  AUGMENTATION:
    FLIPS: false
  MODALITIES:
    3D_LABEL: true
    3D_OCCLUDED: false
    3D_OCCUPANCY: true
    PANOPTIC: false
    PREPROCESS: true
  ROOT_DIR: ../semanticKITTI
  SPLIT:
    TEST: 3901
    TRAIN: 3834
    VAL: 815
  TYPE: SemanticKITTI
MODEL:
  TYPE: LMSCNet_SS
OPTIMIZER:
  BASE_LR: 0.001
  BETA1: 0.9
  BETA2: 0.999
  MOMENTUM: NA
  TYPE: Adam
  WEIGHT_DECAY: NA
OUTPUT:
  BEST_LOSS: 999999999999
  BEST_METRIC: -999999999999
  OUTPUT_PATH: ./SSC_out
  OUT_ROOT: ./SSC_out/
SCHEDULER:
  FREQUENCY: epoch
  LR_POWER: 0.98
  TYPE: power_iteration
STATUS:
  CONFIG: configs/LMSCNet_SS.yaml
  LAST: ./SSC_out/chkpt/02
  RESUME: true
TRAIN:
  BATCH_SIZE: 2
  CHECKPOINT_PERIOD: 15
  EPOCHS: 80
  SUMMARY_PERIOD: 50
VAL:
  BATCH_SIZE: 1
  SUMMARY_PERIOD: 20
